[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"

# Optional: cache node_modules for faster builds
[build.processing]
  skip_processing = true
